project:
  type: website
  output-dir: docs

execute:
  freeze: auto

website:
  repo-url: https://github.com/julianbaltuttis/testing-quarto/
  repo-actions: [ edit, issue ]
  repo-branch: master
  title: "SiA"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: mathematics.qmd
        text: Math
      - about.qmd
format:
  html:
    theme: Minty
    css: styles.css
    toc: true



